use_frameworks!

platform :ios, '13.0'

target 'LLAboutViewController_Example' do
  pod 'LLAboutViewController', :path => '../'

  target 'LLAboutViewController_Tests' do
    inherit! :search_paths

    
  end
end
